default[:openstack][:roles][:database] = 'openstack-mysql'
default[:openstack][:roles][:keystone] = 'openstack-keystone'
default[:openstack][:roles][:ampq] = 'openstack-rabbitmq'
default[:openstack][:roles][:glance] = 'glance-api'
default[:openstack][:roles][:quantum] = 'openstack-network'
default[:openstack][:roles][:quantum_metadata_agent] = 'quantum-metadata-agent'
default[:openstack][:roles][:novnc] = 'nova-novncproxy'
default[:openstack][:roles][:cinder] = 'cinder-api'

default[:openstack][:cloud_archive_url] = 'http://ubuntu-cloud.archive.canonical.com/ubuntu'
